### ISSUE TITLE
Hive-state

### ISSUE THREAD

**Issue by dpdanpittman** [nicholas-2/steem-state#5]
Hi, 

Do you have a working version of this for hive?

**Comment by charette-sh** [comment]
I have not tested this on hive, but it might work on Hive with some changes. I'm not sure what the differences between the two chains are since I haven't used either in a long time. Hive is just a fork of Steem as far as I know, so they should be mostly compatible. It might be that all you have to do is switch the node you use, although there might be differences between the chains that necessitate a different API. If there's some drop-in replacement for `dsteem` that's designed for the Hive blockchain, you could make a fork of this project and change the `dsteem` dependency, and the code would work properly.

So, no, I don't have a working version of this for hive but it could probably work with the fork if the two chains have enough similarities.

**Comment by dpdanpittman** [comment]
Hi,

They were similar but have made changes so now it doesn't work anymore.   I
did just switch stuff to dhive but that no longer works.

**Comment by charette-sh** [comment]
I'm sorry, but I can't make the time investment at the moment to make this project work on dhive. If you can send me information about where the errors are, I'll help you fix them, but debugging this isn't a project I want to undertake at the moment.

**Comment by dpdanpittman** [comment]
No worries,  it seems to work still so we are all good.  Ill create a fork
for hive.  Thanks for your response.
